// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * e​n
	 */
	Language: string
	/**
	 * A​b​o​u​t
	 */
	About: string
}

export type TranslationFunctions = {
	/**
	 * en
	 */
	Language: () => LocalizedString
	/**
	 * About
	 */
	About: () => LocalizedString
}

export type Formatters = {}
